services:
  backend:
    build: 
      context: ./backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  
  # frontend
  frontend:
    build: 
      context: ./frontend
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

volume:
  react_build